switches:
  - name: s11
    id: 11
    type: spine
  - name: s12
    id: 12
    type: spine
  - name: s13
    id: 13
    type: spine

  - name: s21
    id: 21
    type: leaf
  - name: s22
    id: 22
    type: leaf
  - name: s23
    id: 23
    type: leaf
  - name: s24
    id: 24
    type: leaf
  - name: s25
    id: 25
    type: leaf
  - name: s26
    id: 26
    type: leaf

hosts:
  - name: h1
    ip: 10.1.1.1
    mac: 00:00:00:00:00:01
    default_route: "via 10.1.1.100"
    connected_to: s21
    port: 4
  - name: h2
    ip: 10.1.1.2
    mac: 00:00:00:00:00:02
    default_route: "via 10.1.1.100"
    connected_to: s21
    port: 5

  - name: h3
    ip: 10.1.1.3
    mac: 00:00:00:00:00:03
    default_route: "via 10.1.1.100"
    connected_to: s22
    port: 4
  - name: h4
    ip: 10.1.1.4
    mac: 00:00:00:00:00:04
    default_route: "via 10.1.1.100"
    connected_to: s22
    port: 5

  - name: h5
    ip: 10.1.1.5
    mac: 00:00:00:00:00:05
    default_route: "via 10.1.1.100"
    connected_to: s23
    port: 4
  - name: h6
    ip: 10.1.1.6
    mac: 00:00:00:00:00:06
    default_route: "via 10.1.1.100"
    connected_to: s23
    port: 5

  - name: h7
    ip: 10.1.1.7
    mac: 00:00:00:00:00:07
    default_route: "via 10.1.1.100"
    connected_to: s24
    port: 4
  - name: h8
    ip: 10.1.1.8
    mac: 00:00:00:00:00:08
    default_route: "via 10.1.1.100"
    connected_to: s24
    port: 5

  - name: h9
    ip: 10.1.1.9
    mac: 00:00:00:00:00:09
    default_route: "via 10.1.1.100"
    connected_to: s25
    port: 4
  - name: h10
    ip: 10.1.1.10
    mac: 00:00:00:00:00:0A
    default_route: "via 10.1.1.100"
    connected_to: s25
    port: 5

  - name: h11
    ip: 10.1.1.11
    mac: 00:00:00:00:00:0B
    default_route: "via 10.1.1.100"
    connected_to: s26
    port: 4
  - name: h12
    ip: 10.1.1.12
    mac: 00:00:00:00:00:0C
    default_route: "via 10.1.1.100"
    connected_to: s26
    port: 5

links:
  # spine s11 to all leaves
  - source: s11
    source_port: 1
    target: s21
    target_port: 1
  - source: s11
    source_port: 2
    target: s22
    target_port: 1
  - source: s11
    source_port: 3
    target: s23
    target_port: 1
  - source: s11
    source_port: 4
    target: s24
    target_port: 1
  - source: s11
    source_port: 5
    target: s25
    target_port: 1
  - source: s11
    source_port: 6
    target: s26
    target_port: 1

  # spine s12 to all leaves
  - source: s12
    source_port: 1
    target: s21
    target_port: 2
  - source: s12
    source_port: 2
    target: s22
    target_port: 2
  - source: s12
    source_port: 3
    target: s23
    target_port: 2
  - source: s12
    source_port: 4
    target: s24
    target_port: 2
  - source: s12
    source_port: 5
    target: s25
    target_port: 2
  - source: s12
    source_port: 6
    target: s26
    target_port: 2

  # spine s13 to all leaves
  - source: s13
    source_port: 1
    target: s21
    target_port: 3
  - source: s13
    source_port: 2
    target: s22
    target_port: 3
  - source: s13
    source_port: 3
    target: s23
    target_port: 3
  - source: s13
    source_port: 4
    target: s24
    target_port: 3
  - source: s13
    source_port: 5
    target: s25
    target_port: 3
  - source: s13
    source_port: 6
    target: s26
    target_port: 3
